import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Particles } from "@/components/home/support/particles";
import Header from "@/components/home/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
